// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"github.com/google/uuid"
)

// CreateProjectParams is parameters of create_project operation.
type CreateProjectParams struct {
	// Workspace slug.
	Slug string
}

// CreateStateParams is parameters of create_state operation.
type CreateStateParams struct {
	// Project ID.
	ProjectID uuid.UUID
	// Workspace slug.
	Slug string
}

// CreateWorkItem2Params is parameters of create_work_item_2 operation.
type CreateWorkItem2Params struct {
	// Project ID.
	ProjectID uuid.UUID
	// Workspace slug.
	Slug string
}

// DeleteProjectParams is parameters of delete_project operation.
type DeleteProjectParams struct {
	// Project ID.
	Pk uuid.UUID
	// Workspace slug.
	Slug string
}

// DeleteWorkItem2Params is parameters of delete_work_item_2 operation.
type DeleteWorkItem2Params struct {
	Pk uuid.UUID
	// Project ID.
	ProjectID uuid.UUID
	// Workspace slug.
	Slug string
}

// GetWorkspaceWorkItem2Params is parameters of get_workspace_work_item_2 operation.
type GetWorkspaceWorkItem2Params struct {
	// Issue sequence ID (numeric identifier within project).
	IssueIdentifier int
	// Project identifier (unique string within workspace).
	ProjectIdentifier string
	// Workspace slug.
	Slug string
}

// ListProjectsParams is parameters of list_projects operation.
type ListProjectsParams struct {
	// Pagination cursor for getting next set of results.
	Cursor OptString `json:",omitempty,omitzero"`
	// Comma-separated list of related fields to expand in response.
	Expand OptString `json:",omitempty,omitzero"`
	// Comma-separated list of fields to include in response.
	Fields OptString `json:",omitempty,omitzero"`
	// Field to order results by. Prefix with '-' for descending order.
	OrderBy OptString `json:",omitempty,omitzero"`
	// Number of results per page (default: 20, max: 100).
	PerPage OptInt `json:",omitempty,omitzero"`
	// Workspace slug.
	Slug string
}

// ListStatesParams is parameters of list_states operation.
type ListStatesParams struct {
	// Pagination cursor for getting next set of results.
	Cursor OptString `json:",omitempty,omitzero"`
	// Comma-separated list of related fields to expand in response.
	Expand OptString `json:",omitempty,omitzero"`
	// Comma-separated list of fields to include in response.
	Fields OptString `json:",omitempty,omitzero"`
	// Number of results per page (default: 20, max: 100).
	PerPage OptInt `json:",omitempty,omitzero"`
	// Project ID.
	ProjectID uuid.UUID
	// Workspace slug.
	Slug string
}

// ListWorkItems2Params is parameters of list_work_items_2 operation.
type ListWorkItems2Params struct {
	// Pagination cursor for getting next set of results.
	Cursor OptString `json:",omitempty,omitzero"`
	// Comma-separated list of related fields to expand in response.
	Expand OptString `json:",omitempty,omitzero"`
	// External system identifier for filtering or lookup.
	ExternalID OptString `json:",omitempty,omitzero"`
	// External system source name for filtering or lookup.
	ExternalSource OptString `json:",omitempty,omitzero"`
	// Comma-separated list of fields to include in response.
	Fields OptString `json:",omitempty,omitzero"`
	// Field to order results by. Prefix with '-' for descending order.
	OrderBy OptString `json:",omitempty,omitzero"`
	// Number of results per page (default: 20, max: 100).
	PerPage OptInt `json:",omitempty,omitzero"`
	// Project ID.
	ProjectID uuid.UUID
	// Workspace slug.
	Slug string
}

// RetrieveProjectParams is parameters of retrieve_project operation.
type RetrieveProjectParams struct {
	// Project ID.
	Pk uuid.UUID
	// Workspace slug.
	Slug string
}

// RetrieveWorkItem2Params is parameters of retrieve_work_item_2 operation.
type RetrieveWorkItem2Params struct {
	// Comma-separated list of related fields to expand in response.
	Expand OptString `json:",omitempty,omitzero"`
	// External system identifier for filtering or lookup.
	ExternalID OptString `json:",omitempty,omitzero"`
	// External system source name for filtering or lookup.
	ExternalSource OptString `json:",omitempty,omitzero"`
	// Comma-separated list of fields to include in response.
	Fields OptString `json:",omitempty,omitzero"`
	// Field to order results by. Prefix with '-' for descending order.
	OrderBy OptString `json:",omitempty,omitzero"`
	Pk      uuid.UUID
	// Project ID.
	ProjectID uuid.UUID
	// Workspace slug.
	Slug string
}

// UpdateProjectParams is parameters of update_project operation.
type UpdateProjectParams struct {
	// Project ID.
	Pk uuid.UUID
	// Workspace slug.
	Slug string
}

// UpdateWorkItem2Params is parameters of update_work_item_2 operation.
type UpdateWorkItem2Params struct {
	Pk uuid.UUID
	// Project ID.
	ProjectID uuid.UUID
	// Workspace slug.
	Slug string
}
