// Code generated by ogen, DO NOT EDIT.

package oas

// OperationName is the ogen operation name
type OperationName = string

const (
	CreateProjectOperation         OperationName = "CreateProject"
	CreateStateOperation           OperationName = "CreateState"
	CreateWorkItem2Operation       OperationName = "CreateWorkItem2"
	DeleteProjectOperation         OperationName = "DeleteProject"
	DeleteWorkItem2Operation       OperationName = "DeleteWorkItem2"
	GetWorkspaceWorkItem2Operation OperationName = "GetWorkspaceWorkItem2"
	ListProjectsOperation          OperationName = "ListProjects"
	ListStatesOperation            OperationName = "ListStates"
	ListWorkItems2Operation        OperationName = "ListWorkItems2"
	RetrieveProjectOperation       OperationName = "RetrieveProject"
	RetrieveWorkItem2Operation     OperationName = "RetrieveWorkItem2"
	UpdateProjectOperation         OperationName = "UpdateProject"
	UpdateWorkItem2Operation       OperationName = "UpdateWorkItem2"
)
