// Code generated by ogen, DO NOT EDIT.
package oas

type CreateProjectReq interface {
	createProjectReq()
}

type CreateProjectRes interface {
	createProjectRes()
}

type CreateStateReq interface {
	createStateReq()
}

type CreateStateRes interface {
	createStateRes()
}

type CreateWorkItem2Req interface {
	createWorkItem2Req()
}

type CreateWorkItem2Res interface {
	createWorkItem2Res()
}

type DeleteProjectRes interface {
	deleteProjectRes()
}

type DeleteWorkItem2Res interface {
	deleteWorkItem2Res()
}

type GetWorkspaceWorkItem2Res interface {
	getWorkspaceWorkItem2Res()
}

type ListProjectsRes interface {
	listProjectsRes()
}

type ListStatesRes interface {
	listStatesRes()
}

type ListWorkItems2Res interface {
	listWorkItems2Res()
}

type RetrieveProjectRes interface {
	retrieveProjectRes()
}

type RetrieveWorkItem2Res interface {
	retrieveWorkItem2Res()
}

type UpdateProjectReq interface {
	updateProjectReq()
}

type UpdateProjectRes interface {
	updateProjectRes()
}

type UpdateWorkItem2Req interface {
	updateWorkItem2Req()
}

type UpdateWorkItem2Res interface {
	updateWorkItem2Res()
}
