// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
	"net/http"

	"github.com/go-faster/errors"
)

// SecuritySource is provider of security values (tokens, passwords, etc.).
type SecuritySource interface {
	// ApiKeyAuthentication provides ApiKeyAuthentication security value.
	// API key authentication. Provide your API key in the X-API-Key header.
	ApiKeyAuthentication(ctx context.Context, operationName OperationName) (ApiKeyAuthentication, error)
}

// operationRolesApiKeyAuthentication is a private map storing roles per operation.
var operationRolesApiKeyAuthentication = map[string][]string{
	CreateProjectOperation:         []string{},
	CreateStateOperation:           []string{},
	CreateWorkItem2Operation:       []string{},
	DeleteProjectOperation:         []string{},
	DeleteWorkItem2Operation:       []string{},
	GetWorkspaceWorkItem2Operation: []string{},
	ListProjectsOperation:          []string{},
	ListStatesOperation:            []string{},
	ListWorkItems2Operation:        []string{},
	RetrieveProjectOperation:       []string{},
	RetrieveWorkItem2Operation:     []string{},
	UpdateProjectOperation:         []string{},
	UpdateWorkItem2Operation:       []string{},
}

// GetRolesForApiKeyAuthentication returns the required roles for the given operation.
//
// This is useful for authorization scenarios where you need to know which roles
// are required for an operation.
//
// Example:
//
//	requiredRoles := GetRolesForApiKeyAuthentication(AddPetOperation)
//
// Returns nil if the operation has no role requirements or if the operation is unknown.
func GetRolesForApiKeyAuthentication(operation string) []string {
	roles, ok := operationRolesApiKeyAuthentication[operation]
	if !ok {
		return nil
	}
	// Return a copy to prevent external modification
	result := make([]string, len(roles))
	copy(result, roles)
	return result
}

func (s *Client) securityApiKeyAuthentication(ctx context.Context, operationName OperationName, req *http.Request) error {
	t, err := s.sec.ApiKeyAuthentication(ctx, operationName)
	if err != nil {
		return errors.Wrap(err, "security source \"ApiKeyAuthentication\"")
	}
	req.Header.Set("X-API-Key", t.APIKey)
	return nil
}
