// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"fmt"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/validate"
)

func (s *CreateProjectApplicationJSON) Validate() error {
	alias := (*ProjectCreateRequest)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *CreateProjectApplicationXWwwFormUrlencoded) Validate() error {
	alias := (*ProjectCreateRequest)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *CreateStateApplicationJSON) Validate() error {
	alias := (*StateRequest)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *CreateStateApplicationXWwwFormUrlencoded) Validate() error {
	alias := (*StateRequest)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *CreateWorkItem2ApplicationJSON) Validate() error {
	alias := (*IssueRequest)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *CreateWorkItem2ApplicationXWwwFormUrlencoded) Validate() error {
	alias := (*IssueRequest)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s GroupEnum) Validate() error {
	switch s {
	case "backlog":
		return nil
	case "unstarted":
		return nil
	case "started":
		return nil
	case "completed":
		return nil
	case "cancelled":
		return nil
	case "triage":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *Issue) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.Point.Get(); ok {
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           0,
					MaxSet:        true,
					Max:           12,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
					Pattern:       nil,
				}).Validate(int64(value)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "point",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.String{
			MinLength:     0,
			MinLengthSet:  false,
			MaxLength:     255,
			MaxLengthSet:  true,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.Name)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "name",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Priority.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "priority",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.SequenceID.Get(); ok {
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           -9223372036854775808,
					MaxSet:        true,
					Max:           9223372036854775807,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
					Pattern:       nil,
				}).Validate(int64(value)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "sequence_id",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.SortOrder.Get(); ok {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "sort_order",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ExternalSource.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     255,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "external_source",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ExternalID.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     255,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "external_id",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *IssueRequest) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.Point.Get(); ok {
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           0,
					MaxSet:        true,
					Max:           12,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
					Pattern:       nil,
				}).Validate(int64(value)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "point",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.String{
			MinLength:     1,
			MinLengthSet:  true,
			MaxLength:     255,
			MaxLengthSet:  true,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.Name)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "name",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Priority.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "priority",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.SequenceID.Get(); ok {
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           -9223372036854775808,
					MaxSet:        true,
					Max:           9223372036854775807,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
					Pattern:       nil,
				}).Validate(int64(value)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "sequence_id",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.SortOrder.Get(); ok {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "sort_order",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ExternalSource.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     255,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "external_source",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ExternalID.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     255,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "external_id",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *IssueRequestMultipart) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.Point.Get(); ok {
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           0,
					MaxSet:        true,
					Max:           12,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
					Pattern:       nil,
				}).Validate(int64(value)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "point",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.String{
			MinLength:     1,
			MinLengthSet:  true,
			MaxLength:     255,
			MaxLengthSet:  true,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.Name)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "name",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Priority.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "priority",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.SequenceID.Get(); ok {
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           -9223372036854775808,
					MaxSet:        true,
					Max:           9223372036854775807,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
					Pattern:       nil,
				}).Validate(int64(value)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "sequence_id",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.SortOrder.Get(); ok {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "sort_order",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ExternalSource.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     255,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "external_source",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ExternalID.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     255,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "external_id",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *PaginatedProjectResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.Results == nil {
			return errors.New("nil is invalid value")
		}
		var failures []validate.FieldError
		for i, elem := range s.Results {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "results",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *PaginatedStateResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.Results == nil {
			return errors.New("nil is invalid value")
		}
		var failures []validate.FieldError
		for i, elem := range s.Results {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "results",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *PaginatedWorkItemResponse) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.Results == nil {
			return errors.New("nil is invalid value")
		}
		var failures []validate.FieldError
		for i, elem := range s.Results {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "results",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *PatchedIssueRequest) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.Point.Get(); ok {
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           0,
					MaxSet:        true,
					Max:           12,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
					Pattern:       nil,
				}).Validate(int64(value)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "point",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Name.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     1,
					MinLengthSet:  true,
					MaxLength:     255,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "name",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Priority.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "priority",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.SequenceID.Get(); ok {
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           -9223372036854775808,
					MaxSet:        true,
					Max:           9223372036854775807,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
					Pattern:       nil,
				}).Validate(int64(value)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "sequence_id",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.SortOrder.Get(); ok {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "sort_order",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ExternalSource.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     255,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "external_source",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ExternalID.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     255,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "external_id",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *PatchedIssueRequestMultipart) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.Point.Get(); ok {
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           0,
					MaxSet:        true,
					Max:           12,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
					Pattern:       nil,
				}).Validate(int64(value)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "point",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Name.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     1,
					MinLengthSet:  true,
					MaxLength:     255,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "name",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Priority.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "priority",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.SequenceID.Get(); ok {
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           -9223372036854775808,
					MaxSet:        true,
					Max:           9223372036854775807,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
					Pattern:       nil,
				}).Validate(int64(value)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "sequence_id",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.SortOrder.Get(); ok {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "sort_order",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ExternalSource.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     255,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "external_source",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ExternalID.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     255,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "external_id",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *PatchedProjectUpdateRequest) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.Name.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     1,
					MinLengthSet:  true,
					MaxLength:     255,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "name",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Identifier.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     1,
					MinLengthSet:  true,
					MaxLength:     12,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "identifier",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Emoji.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     255,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "emoji",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ArchiveIn.Get(); ok {
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           0,
					MaxSet:        true,
					Max:           12,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
					Pattern:       nil,
				}).Validate(int64(value)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "archive_in",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.CloseIn.Get(); ok {
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           0,
					MaxSet:        true,
					Max:           12,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
					Pattern:       nil,
				}).Validate(int64(value)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "close_in",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Timezone.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "timezone",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ExternalSource.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     255,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "external_source",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ExternalID.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     255,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "external_id",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *PatchedProjectUpdateRequestMultipart) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.Name.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     1,
					MinLengthSet:  true,
					MaxLength:     255,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "name",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Identifier.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     1,
					MinLengthSet:  true,
					MaxLength:     12,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "identifier",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Emoji.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     255,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "emoji",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ArchiveIn.Get(); ok {
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           0,
					MaxSet:        true,
					Max:           12,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
					Pattern:       nil,
				}).Validate(int64(value)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "archive_in",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.CloseIn.Get(); ok {
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           0,
					MaxSet:        true,
					Max:           12,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
					Pattern:       nil,
				}).Validate(int64(value)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "close_in",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Timezone.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "timezone",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ExternalSource.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     255,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "external_source",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ExternalID.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     255,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "external_id",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s PriorityEnum) Validate() error {
	switch s {
	case "urgent":
		return nil
	case "high":
		return nil
	case "medium":
		return nil
	case "low":
		return nil
	case "none":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *Project) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if value, ok := s.SortOrder.Get(); ok {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "sort_order",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.String{
			MinLength:     0,
			MinLengthSet:  false,
			MaxLength:     255,
			MaxLengthSet:  true,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.Name)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "name",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Network.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "network",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.String{
			MinLength:     0,
			MinLengthSet:  false,
			MaxLength:     12,
			MaxLengthSet:  true,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.Identifier)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "identifier",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ArchiveIn.Get(); ok {
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           0,
					MaxSet:        true,
					Max:           12,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
					Pattern:       nil,
				}).Validate(int64(value)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "archive_in",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.CloseIn.Get(); ok {
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           0,
					MaxSet:        true,
					Max:           12,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
					Pattern:       nil,
				}).Validate(int64(value)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "close_in",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Timezone.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "timezone",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ExternalSource.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     255,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "external_source",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ExternalID.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     255,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "external_id",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *ProjectCreateRequest) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.String{
			MinLength:     1,
			MinLengthSet:  true,
			MaxLength:     255,
			MaxLengthSet:  true,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.Name)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "name",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.String{
			MinLength:     1,
			MinLengthSet:  true,
			MaxLength:     12,
			MaxLengthSet:  true,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.Identifier)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "identifier",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Emoji.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     255,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "emoji",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ArchiveIn.Get(); ok {
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           0,
					MaxSet:        true,
					Max:           12,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
					Pattern:       nil,
				}).Validate(int64(value)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "archive_in",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.CloseIn.Get(); ok {
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           0,
					MaxSet:        true,
					Max:           12,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
					Pattern:       nil,
				}).Validate(int64(value)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "close_in",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Timezone.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "timezone",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ExternalSource.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     255,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "external_source",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ExternalID.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     255,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "external_id",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *ProjectCreateRequestMultipart) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.String{
			MinLength:     1,
			MinLengthSet:  true,
			MaxLength:     255,
			MaxLengthSet:  true,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.Name)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "name",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.String{
			MinLength:     1,
			MinLengthSet:  true,
			MaxLength:     12,
			MaxLengthSet:  true,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.Identifier)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "identifier",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Emoji.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     255,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "emoji",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ArchiveIn.Get(); ok {
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           0,
					MaxSet:        true,
					Max:           12,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
					Pattern:       nil,
				}).Validate(int64(value)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "archive_in",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.CloseIn.Get(); ok {
			if err := func() error {
				if err := (validate.Int{
					MinSet:        true,
					Min:           0,
					MaxSet:        true,
					Max:           12,
					MinExclusive:  false,
					MaxExclusive:  false,
					MultipleOfSet: false,
					MultipleOf:    0,
					Pattern:       nil,
				}).Validate(int64(value)); err != nil {
					return errors.Wrap(err, "int")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "close_in",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Timezone.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "timezone",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ExternalSource.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     255,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "external_source",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ExternalID.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     255,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "external_id",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s ProjectNetwork) Validate() error {
	switch s {
	case 0:
		return nil
	case 2:
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *State) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.String{
			MinLength:     0,
			MinLengthSet:  false,
			MaxLength:     255,
			MaxLengthSet:  true,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.Name)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "name",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.String{
			MinLength:     0,
			MinLengthSet:  false,
			MaxLength:     255,
			MaxLengthSet:  true,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.Color)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "color",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Slug.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     0,
					MaxLengthSet:  false,
					Email:         false,
					Hostname:      false,
					Regex:         regexMap["^[-a-zA-Z0-9_]+$"],
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "slug",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Sequence.Get(); ok {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "sequence",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Group.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "group",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ExternalSource.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     255,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "external_source",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ExternalID.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     255,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "external_id",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *StateRequest) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.String{
			MinLength:     1,
			MinLengthSet:  true,
			MaxLength:     255,
			MaxLengthSet:  true,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.Name)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "name",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.String{
			MinLength:     1,
			MinLengthSet:  true,
			MaxLength:     255,
			MaxLengthSet:  true,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.Color)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "color",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Sequence.Get(); ok {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "sequence",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Group.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "group",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ExternalSource.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     255,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "external_source",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ExternalID.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     255,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "external_id",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *StateRequestMultipart) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.String{
			MinLength:     1,
			MinLengthSet:  true,
			MaxLength:     255,
			MaxLengthSet:  true,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.Name)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "name",
			Error: err,
		})
	}
	if err := func() error {
		if err := (validate.String{
			MinLength:     1,
			MinLengthSet:  true,
			MaxLength:     255,
			MaxLengthSet:  true,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.Color)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "color",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Sequence.Get(); ok {
			if err := func() error {
				if err := (validate.Float{}).Validate(float64(value)); err != nil {
					return errors.Wrap(err, "float")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "sequence",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.Group.Get(); ok {
			if err := func() error {
				if err := value.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "group",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ExternalSource.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     255,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "external_source",
			Error: err,
		})
	}
	if err := func() error {
		if value, ok := s.ExternalID.Get(); ok {
			if err := func() error {
				if err := (validate.String{
					MinLength:     0,
					MinLengthSet:  false,
					MaxLength:     255,
					MaxLengthSet:  true,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(value)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "external_id",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s TimezoneEnum) Validate() error {
	switch s {
	case "Africa/Abidjan":
		return nil
	case "Africa/Accra":
		return nil
	case "Africa/Addis_Ababa":
		return nil
	case "Africa/Algiers":
		return nil
	case "Africa/Asmara":
		return nil
	case "Africa/Bamako":
		return nil
	case "Africa/Bangui":
		return nil
	case "Africa/Banjul":
		return nil
	case "Africa/Bissau":
		return nil
	case "Africa/Blantyre":
		return nil
	case "Africa/Brazzaville":
		return nil
	case "Africa/Bujumbura":
		return nil
	case "Africa/Cairo":
		return nil
	case "Africa/Casablanca":
		return nil
	case "Africa/Ceuta":
		return nil
	case "Africa/Conakry":
		return nil
	case "Africa/Dakar":
		return nil
	case "Africa/Dar_es_Salaam":
		return nil
	case "Africa/Djibouti":
		return nil
	case "Africa/Douala":
		return nil
	case "Africa/El_Aaiun":
		return nil
	case "Africa/Freetown":
		return nil
	case "Africa/Gaborone":
		return nil
	case "Africa/Harare":
		return nil
	case "Africa/Johannesburg":
		return nil
	case "Africa/Juba":
		return nil
	case "Africa/Kampala":
		return nil
	case "Africa/Khartoum":
		return nil
	case "Africa/Kigali":
		return nil
	case "Africa/Kinshasa":
		return nil
	case "Africa/Lagos":
		return nil
	case "Africa/Libreville":
		return nil
	case "Africa/Lome":
		return nil
	case "Africa/Luanda":
		return nil
	case "Africa/Lubumbashi":
		return nil
	case "Africa/Lusaka":
		return nil
	case "Africa/Malabo":
		return nil
	case "Africa/Maputo":
		return nil
	case "Africa/Maseru":
		return nil
	case "Africa/Mbabane":
		return nil
	case "Africa/Mogadishu":
		return nil
	case "Africa/Monrovia":
		return nil
	case "Africa/Nairobi":
		return nil
	case "Africa/Ndjamena":
		return nil
	case "Africa/Niamey":
		return nil
	case "Africa/Nouakchott":
		return nil
	case "Africa/Ouagadougou":
		return nil
	case "Africa/Porto-Novo":
		return nil
	case "Africa/Sao_Tome":
		return nil
	case "Africa/Tripoli":
		return nil
	case "Africa/Tunis":
		return nil
	case "Africa/Windhoek":
		return nil
	case "America/Adak":
		return nil
	case "America/Anchorage":
		return nil
	case "America/Anguilla":
		return nil
	case "America/Antigua":
		return nil
	case "America/Araguaina":
		return nil
	case "America/Argentina/Buenos_Aires":
		return nil
	case "America/Argentina/Catamarca":
		return nil
	case "America/Argentina/Cordoba":
		return nil
	case "America/Argentina/Jujuy":
		return nil
	case "America/Argentina/La_Rioja":
		return nil
	case "America/Argentina/Mendoza":
		return nil
	case "America/Argentina/Rio_Gallegos":
		return nil
	case "America/Argentina/Salta":
		return nil
	case "America/Argentina/San_Juan":
		return nil
	case "America/Argentina/San_Luis":
		return nil
	case "America/Argentina/Tucuman":
		return nil
	case "America/Argentina/Ushuaia":
		return nil
	case "America/Aruba":
		return nil
	case "America/Asuncion":
		return nil
	case "America/Atikokan":
		return nil
	case "America/Bahia":
		return nil
	case "America/Bahia_Banderas":
		return nil
	case "America/Barbados":
		return nil
	case "America/Belem":
		return nil
	case "America/Belize":
		return nil
	case "America/Blanc-Sablon":
		return nil
	case "America/Boa_Vista":
		return nil
	case "America/Bogota":
		return nil
	case "America/Boise":
		return nil
	case "America/Cambridge_Bay":
		return nil
	case "America/Campo_Grande":
		return nil
	case "America/Cancun":
		return nil
	case "America/Caracas":
		return nil
	case "America/Cayenne":
		return nil
	case "America/Cayman":
		return nil
	case "America/Chicago":
		return nil
	case "America/Chihuahua":
		return nil
	case "America/Ciudad_Juarez":
		return nil
	case "America/Costa_Rica":
		return nil
	case "America/Creston":
		return nil
	case "America/Cuiaba":
		return nil
	case "America/Curacao":
		return nil
	case "America/Danmarkshavn":
		return nil
	case "America/Dawson":
		return nil
	case "America/Dawson_Creek":
		return nil
	case "America/Denver":
		return nil
	case "America/Detroit":
		return nil
	case "America/Dominica":
		return nil
	case "America/Edmonton":
		return nil
	case "America/Eirunepe":
		return nil
	case "America/El_Salvador":
		return nil
	case "America/Fort_Nelson":
		return nil
	case "America/Fortaleza":
		return nil
	case "America/Glace_Bay":
		return nil
	case "America/Goose_Bay":
		return nil
	case "America/Grand_Turk":
		return nil
	case "America/Grenada":
		return nil
	case "America/Guadeloupe":
		return nil
	case "America/Guatemala":
		return nil
	case "America/Guayaquil":
		return nil
	case "America/Guyana":
		return nil
	case "America/Halifax":
		return nil
	case "America/Havana":
		return nil
	case "America/Hermosillo":
		return nil
	case "America/Indiana/Indianapolis":
		return nil
	case "America/Indiana/Knox":
		return nil
	case "America/Indiana/Marengo":
		return nil
	case "America/Indiana/Petersburg":
		return nil
	case "America/Indiana/Tell_City":
		return nil
	case "America/Indiana/Vevay":
		return nil
	case "America/Indiana/Vincennes":
		return nil
	case "America/Indiana/Winamac":
		return nil
	case "America/Inuvik":
		return nil
	case "America/Iqaluit":
		return nil
	case "America/Jamaica":
		return nil
	case "America/Juneau":
		return nil
	case "America/Kentucky/Louisville":
		return nil
	case "America/Kentucky/Monticello":
		return nil
	case "America/Kralendijk":
		return nil
	case "America/La_Paz":
		return nil
	case "America/Lima":
		return nil
	case "America/Los_Angeles":
		return nil
	case "America/Lower_Princes":
		return nil
	case "America/Maceio":
		return nil
	case "America/Managua":
		return nil
	case "America/Manaus":
		return nil
	case "America/Marigot":
		return nil
	case "America/Martinique":
		return nil
	case "America/Matamoros":
		return nil
	case "America/Mazatlan":
		return nil
	case "America/Menominee":
		return nil
	case "America/Merida":
		return nil
	case "America/Metlakatla":
		return nil
	case "America/Mexico_City":
		return nil
	case "America/Miquelon":
		return nil
	case "America/Moncton":
		return nil
	case "America/Monterrey":
		return nil
	case "America/Montevideo":
		return nil
	case "America/Montserrat":
		return nil
	case "America/Nassau":
		return nil
	case "America/New_York":
		return nil
	case "America/Nome":
		return nil
	case "America/Noronha":
		return nil
	case "America/North_Dakota/Beulah":
		return nil
	case "America/North_Dakota/Center":
		return nil
	case "America/North_Dakota/New_Salem":
		return nil
	case "America/Nuuk":
		return nil
	case "America/Ojinaga":
		return nil
	case "America/Panama":
		return nil
	case "America/Paramaribo":
		return nil
	case "America/Phoenix":
		return nil
	case "America/Port-au-Prince":
		return nil
	case "America/Port_of_Spain":
		return nil
	case "America/Porto_Velho":
		return nil
	case "America/Puerto_Rico":
		return nil
	case "America/Punta_Arenas":
		return nil
	case "America/Rankin_Inlet":
		return nil
	case "America/Recife":
		return nil
	case "America/Regina":
		return nil
	case "America/Resolute":
		return nil
	case "America/Rio_Branco":
		return nil
	case "America/Santarem":
		return nil
	case "America/Santiago":
		return nil
	case "America/Santo_Domingo":
		return nil
	case "America/Sao_Paulo":
		return nil
	case "America/Scoresbysund":
		return nil
	case "America/Sitka":
		return nil
	case "America/St_Barthelemy":
		return nil
	case "America/St_Johns":
		return nil
	case "America/St_Kitts":
		return nil
	case "America/St_Lucia":
		return nil
	case "America/St_Thomas":
		return nil
	case "America/St_Vincent":
		return nil
	case "America/Swift_Current":
		return nil
	case "America/Tegucigalpa":
		return nil
	case "America/Thule":
		return nil
	case "America/Tijuana":
		return nil
	case "America/Toronto":
		return nil
	case "America/Tortola":
		return nil
	case "America/Vancouver":
		return nil
	case "America/Whitehorse":
		return nil
	case "America/Winnipeg":
		return nil
	case "America/Yakutat":
		return nil
	case "Antarctica/Casey":
		return nil
	case "Antarctica/Davis":
		return nil
	case "Antarctica/DumontDUrville":
		return nil
	case "Antarctica/Macquarie":
		return nil
	case "Antarctica/Mawson":
		return nil
	case "Antarctica/McMurdo":
		return nil
	case "Antarctica/Palmer":
		return nil
	case "Antarctica/Rothera":
		return nil
	case "Antarctica/Syowa":
		return nil
	case "Antarctica/Troll":
		return nil
	case "Antarctica/Vostok":
		return nil
	case "Arctic/Longyearbyen":
		return nil
	case "Asia/Aden":
		return nil
	case "Asia/Almaty":
		return nil
	case "Asia/Amman":
		return nil
	case "Asia/Anadyr":
		return nil
	case "Asia/Aqtau":
		return nil
	case "Asia/Aqtobe":
		return nil
	case "Asia/Ashgabat":
		return nil
	case "Asia/Atyrau":
		return nil
	case "Asia/Baghdad":
		return nil
	case "Asia/Bahrain":
		return nil
	case "Asia/Baku":
		return nil
	case "Asia/Bangkok":
		return nil
	case "Asia/Barnaul":
		return nil
	case "Asia/Beirut":
		return nil
	case "Asia/Bishkek":
		return nil
	case "Asia/Brunei":
		return nil
	case "Asia/Chita":
		return nil
	case "Asia/Choibalsan":
		return nil
	case "Asia/Colombo":
		return nil
	case "Asia/Damascus":
		return nil
	case "Asia/Dhaka":
		return nil
	case "Asia/Dili":
		return nil
	case "Asia/Dubai":
		return nil
	case "Asia/Dushanbe":
		return nil
	case "Asia/Famagusta":
		return nil
	case "Asia/Gaza":
		return nil
	case "Asia/Hebron":
		return nil
	case "Asia/Ho_Chi_Minh":
		return nil
	case "Asia/Hong_Kong":
		return nil
	case "Asia/Hovd":
		return nil
	case "Asia/Irkutsk":
		return nil
	case "Asia/Jakarta":
		return nil
	case "Asia/Jayapura":
		return nil
	case "Asia/Jerusalem":
		return nil
	case "Asia/Kabul":
		return nil
	case "Asia/Kamchatka":
		return nil
	case "Asia/Karachi":
		return nil
	case "Asia/Kathmandu":
		return nil
	case "Asia/Khandyga":
		return nil
	case "Asia/Kolkata":
		return nil
	case "Asia/Krasnoyarsk":
		return nil
	case "Asia/Kuala_Lumpur":
		return nil
	case "Asia/Kuching":
		return nil
	case "Asia/Kuwait":
		return nil
	case "Asia/Macau":
		return nil
	case "Asia/Magadan":
		return nil
	case "Asia/Makassar":
		return nil
	case "Asia/Manila":
		return nil
	case "Asia/Muscat":
		return nil
	case "Asia/Nicosia":
		return nil
	case "Asia/Novokuznetsk":
		return nil
	case "Asia/Novosibirsk":
		return nil
	case "Asia/Omsk":
		return nil
	case "Asia/Oral":
		return nil
	case "Asia/Phnom_Penh":
		return nil
	case "Asia/Pontianak":
		return nil
	case "Asia/Pyongyang":
		return nil
	case "Asia/Qatar":
		return nil
	case "Asia/Qostanay":
		return nil
	case "Asia/Qyzylorda":
		return nil
	case "Asia/Riyadh":
		return nil
	case "Asia/Sakhalin":
		return nil
	case "Asia/Samarkand":
		return nil
	case "Asia/Seoul":
		return nil
	case "Asia/Shanghai":
		return nil
	case "Asia/Singapore":
		return nil
	case "Asia/Srednekolymsk":
		return nil
	case "Asia/Taipei":
		return nil
	case "Asia/Tashkent":
		return nil
	case "Asia/Tbilisi":
		return nil
	case "Asia/Tehran":
		return nil
	case "Asia/Thimphu":
		return nil
	case "Asia/Tokyo":
		return nil
	case "Asia/Tomsk":
		return nil
	case "Asia/Ulaanbaatar":
		return nil
	case "Asia/Urumqi":
		return nil
	case "Asia/Ust-Nera":
		return nil
	case "Asia/Vientiane":
		return nil
	case "Asia/Vladivostok":
		return nil
	case "Asia/Yakutsk":
		return nil
	case "Asia/Yangon":
		return nil
	case "Asia/Yekaterinburg":
		return nil
	case "Asia/Yerevan":
		return nil
	case "Atlantic/Azores":
		return nil
	case "Atlantic/Bermuda":
		return nil
	case "Atlantic/Canary":
		return nil
	case "Atlantic/Cape_Verde":
		return nil
	case "Atlantic/Faroe":
		return nil
	case "Atlantic/Madeira":
		return nil
	case "Atlantic/Reykjavik":
		return nil
	case "Atlantic/South_Georgia":
		return nil
	case "Atlantic/St_Helena":
		return nil
	case "Atlantic/Stanley":
		return nil
	case "Australia/Adelaide":
		return nil
	case "Australia/Brisbane":
		return nil
	case "Australia/Broken_Hill":
		return nil
	case "Australia/Darwin":
		return nil
	case "Australia/Eucla":
		return nil
	case "Australia/Hobart":
		return nil
	case "Australia/Lindeman":
		return nil
	case "Australia/Lord_Howe":
		return nil
	case "Australia/Melbourne":
		return nil
	case "Australia/Perth":
		return nil
	case "Australia/Sydney":
		return nil
	case "Canada/Atlantic":
		return nil
	case "Canada/Central":
		return nil
	case "Canada/Eastern":
		return nil
	case "Canada/Mountain":
		return nil
	case "Canada/Newfoundland":
		return nil
	case "Canada/Pacific":
		return nil
	case "Europe/Amsterdam":
		return nil
	case "Europe/Andorra":
		return nil
	case "Europe/Astrakhan":
		return nil
	case "Europe/Athens":
		return nil
	case "Europe/Belgrade":
		return nil
	case "Europe/Berlin":
		return nil
	case "Europe/Bratislava":
		return nil
	case "Europe/Brussels":
		return nil
	case "Europe/Bucharest":
		return nil
	case "Europe/Budapest":
		return nil
	case "Europe/Busingen":
		return nil
	case "Europe/Chisinau":
		return nil
	case "Europe/Copenhagen":
		return nil
	case "Europe/Dublin":
		return nil
	case "Europe/Gibraltar":
		return nil
	case "Europe/Guernsey":
		return nil
	case "Europe/Helsinki":
		return nil
	case "Europe/Isle_of_Man":
		return nil
	case "Europe/Istanbul":
		return nil
	case "Europe/Jersey":
		return nil
	case "Europe/Kaliningrad":
		return nil
	case "Europe/Kirov":
		return nil
	case "Europe/Kyiv":
		return nil
	case "Europe/Lisbon":
		return nil
	case "Europe/Ljubljana":
		return nil
	case "Europe/London":
		return nil
	case "Europe/Luxembourg":
		return nil
	case "Europe/Madrid":
		return nil
	case "Europe/Malta":
		return nil
	case "Europe/Mariehamn":
		return nil
	case "Europe/Minsk":
		return nil
	case "Europe/Monaco":
		return nil
	case "Europe/Moscow":
		return nil
	case "Europe/Oslo":
		return nil
	case "Europe/Paris":
		return nil
	case "Europe/Podgorica":
		return nil
	case "Europe/Prague":
		return nil
	case "Europe/Riga":
		return nil
	case "Europe/Rome":
		return nil
	case "Europe/Samara":
		return nil
	case "Europe/San_Marino":
		return nil
	case "Europe/Sarajevo":
		return nil
	case "Europe/Saratov":
		return nil
	case "Europe/Simferopol":
		return nil
	case "Europe/Skopje":
		return nil
	case "Europe/Sofia":
		return nil
	case "Europe/Stockholm":
		return nil
	case "Europe/Tallinn":
		return nil
	case "Europe/Tirane":
		return nil
	case "Europe/Ulyanovsk":
		return nil
	case "Europe/Vaduz":
		return nil
	case "Europe/Vatican":
		return nil
	case "Europe/Vienna":
		return nil
	case "Europe/Vilnius":
		return nil
	case "Europe/Volgograd":
		return nil
	case "Europe/Warsaw":
		return nil
	case "Europe/Zagreb":
		return nil
	case "Europe/Zurich":
		return nil
	case "GMT":
		return nil
	case "Indian/Antananarivo":
		return nil
	case "Indian/Chagos":
		return nil
	case "Indian/Christmas":
		return nil
	case "Indian/Cocos":
		return nil
	case "Indian/Comoro":
		return nil
	case "Indian/Kerguelen":
		return nil
	case "Indian/Mahe":
		return nil
	case "Indian/Maldives":
		return nil
	case "Indian/Mauritius":
		return nil
	case "Indian/Mayotte":
		return nil
	case "Indian/Reunion":
		return nil
	case "Pacific/Apia":
		return nil
	case "Pacific/Auckland":
		return nil
	case "Pacific/Bougainville":
		return nil
	case "Pacific/Chatham":
		return nil
	case "Pacific/Chuuk":
		return nil
	case "Pacific/Easter":
		return nil
	case "Pacific/Efate":
		return nil
	case "Pacific/Fakaofo":
		return nil
	case "Pacific/Fiji":
		return nil
	case "Pacific/Funafuti":
		return nil
	case "Pacific/Galapagos":
		return nil
	case "Pacific/Gambier":
		return nil
	case "Pacific/Guadalcanal":
		return nil
	case "Pacific/Guam":
		return nil
	case "Pacific/Honolulu":
		return nil
	case "Pacific/Kanton":
		return nil
	case "Pacific/Kiritimati":
		return nil
	case "Pacific/Kosrae":
		return nil
	case "Pacific/Kwajalein":
		return nil
	case "Pacific/Majuro":
		return nil
	case "Pacific/Marquesas":
		return nil
	case "Pacific/Midway":
		return nil
	case "Pacific/Nauru":
		return nil
	case "Pacific/Niue":
		return nil
	case "Pacific/Norfolk":
		return nil
	case "Pacific/Noumea":
		return nil
	case "Pacific/Pago_Pago":
		return nil
	case "Pacific/Palau":
		return nil
	case "Pacific/Pitcairn":
		return nil
	case "Pacific/Pohnpei":
		return nil
	case "Pacific/Port_Moresby":
		return nil
	case "Pacific/Rarotonga":
		return nil
	case "Pacific/Saipan":
		return nil
	case "Pacific/Tahiti":
		return nil
	case "Pacific/Tarawa":
		return nil
	case "Pacific/Tongatapu":
		return nil
	case "Pacific/Wake":
		return nil
	case "Pacific/Wallis":
		return nil
	case "US/Alaska":
		return nil
	case "US/Arizona":
		return nil
	case "US/Central":
		return nil
	case "US/Eastern":
		return nil
	case "US/Hawaii":
		return nil
	case "US/Mountain":
		return nil
	case "US/Pacific":
		return nil
	case "UTC":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *UpdateProjectApplicationJSON) Validate() error {
	alias := (*PatchedProjectUpdateRequest)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *UpdateProjectApplicationXWwwFormUrlencoded) Validate() error {
	alias := (*PatchedProjectUpdateRequest)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *UpdateWorkItem2ApplicationJSON) Validate() error {
	alias := (*PatchedIssueRequest)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *UpdateWorkItem2ApplicationXWwwFormUrlencoded) Validate() error {
	alias := (*PatchedIssueRequest)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}
