// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"bytes"
	"fmt"
	"mime"
	"mime/multipart"
	"net/http"
	"strings"

	"github.com/go-faster/errors"
	"github.com/go-faster/jx"
	"github.com/ogen-go/ogen/conv"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/uri"
)

func encodeCreateProjectRequest(
	req CreateProjectReq,
	r *http.Request,
) error {
	switch req := req.(type) {
	case *CreateProjectApplicationJSON:
		const contentType = "application/json"
		e := new(jx.Encoder)
		{
			req.Encode(e)
		}
		encoded := e.Bytes()
		ht.SetBody(r, bytes.NewReader(encoded), contentType)
		return nil
	case *CreateProjectApplicationXWwwFormUrlencoded:
		const contentType = "application/x-www-form-urlencoded"
		request := req

		q := uri.NewFormEncoder(map[string]string{})
		{
			// Encode "name" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "name",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				return e.EncodeValue(conv.StringToString(request.Name))
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "description" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "description",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Description.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "project_lead" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "project_lead",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.ProjectLead.Get(); ok {
					return e.EncodeValue(conv.UUIDToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "default_assignee" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "default_assignee",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.DefaultAssignee.Get(); ok {
					return e.EncodeValue(conv.UUIDToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "identifier" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "identifier",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				return e.EncodeValue(conv.StringToString(request.Identifier))
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "icon_prop" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "icon_prop",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if request.IconProp != nil {
					return e.EncodeValue(fmt.Sprint(request.IconProp))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "emoji" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "emoji",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Emoji.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "cover_image" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "cover_image",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.CoverImage.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "module_view" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "module_view",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.ModuleView.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "cycle_view" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "cycle_view",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.CycleView.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "issue_views_view" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "issue_views_view",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.IssueViewsView.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "page_view" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "page_view",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.PageView.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "intake_view" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "intake_view",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.IntakeView.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "guest_view_all_features" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "guest_view_all_features",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.GuestViewAllFeatures.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "archive_in" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "archive_in",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.ArchiveIn.Get(); ok {
					return e.EncodeValue(conv.IntToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "close_in" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "close_in",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.CloseIn.Get(); ok {
					return e.EncodeValue(conv.IntToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "timezone" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "timezone",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Timezone.Get(); ok {
					return e.EncodeValue(conv.StringToString(string(val)))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "external_source" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "external_source",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.ExternalSource.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "external_id" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "external_id",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.ExternalID.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "is_issue_type_enabled" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "is_issue_type_enabled",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.IsIssueTypeEnabled.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "is_time_tracking_enabled" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "is_time_tracking_enabled",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.IsTimeTrackingEnabled.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		encoded := q.Values().Encode()
		ht.SetBody(r, strings.NewReader(encoded), contentType)
		return nil
	case *ProjectCreateRequestMultipart:
		const contentType = "multipart/form-data"
		request := req

		q := uri.NewFormEncoder(map[string]string{
			"icon_prop": "application/json; charset=utf-8",
		})
		{
			// Encode "name" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "name",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				return e.EncodeValue(conv.StringToString(request.Name))
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "description" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "description",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Description.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "project_lead" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "project_lead",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.ProjectLead.Get(); ok {
					return e.EncodeValue(conv.UUIDToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "default_assignee" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "default_assignee",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.DefaultAssignee.Get(); ok {
					return e.EncodeValue(conv.UUIDToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "identifier" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "identifier",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				return e.EncodeValue(conv.StringToString(request.Identifier))
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "icon_prop" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "icon_prop",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				var enc jx.Encoder
				func(e *jx.Encoder) {
					if len(request.IconProp) != 0 {
						e.Raw(request.IconProp)
					}
				}(&enc)
				return e.EncodeValue(string(enc.Bytes()))
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "emoji" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "emoji",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Emoji.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "cover_image" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "cover_image",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.CoverImage.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "module_view" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "module_view",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.ModuleView.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "cycle_view" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "cycle_view",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.CycleView.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "issue_views_view" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "issue_views_view",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.IssueViewsView.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "page_view" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "page_view",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.PageView.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "intake_view" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "intake_view",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.IntakeView.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "guest_view_all_features" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "guest_view_all_features",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.GuestViewAllFeatures.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "archive_in" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "archive_in",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.ArchiveIn.Get(); ok {
					return e.EncodeValue(conv.IntToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "close_in" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "close_in",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.CloseIn.Get(); ok {
					return e.EncodeValue(conv.IntToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "timezone" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "timezone",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Timezone.Get(); ok {
					return e.EncodeValue(conv.StringToString(string(val)))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "external_source" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "external_source",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.ExternalSource.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "external_id" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "external_id",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.ExternalID.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "is_issue_type_enabled" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "is_issue_type_enabled",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.IsIssueTypeEnabled.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "is_time_tracking_enabled" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "is_time_tracking_enabled",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.IsTimeTrackingEnabled.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		body, boundary := ht.CreateMultipartBody(func(w *multipart.Writer) error {
			if err := q.WriteMultipart(w); err != nil {
				return errors.Wrap(err, "write multipart")
			}
			return nil
		})
		ht.SetCloserBody(r, body, mime.FormatMediaType(contentType, map[string]string{"boundary": boundary}))
		return nil
	default:
		return errors.Errorf("unexpected request type: %T", req)
	}
}

func encodeCreateStateRequest(
	req CreateStateReq,
	r *http.Request,
) error {
	switch req := req.(type) {
	case *CreateStateApplicationJSON:
		const contentType = "application/json"
		e := new(jx.Encoder)
		{
			req.Encode(e)
		}
		encoded := e.Bytes()
		ht.SetBody(r, bytes.NewReader(encoded), contentType)
		return nil
	case *CreateStateApplicationXWwwFormUrlencoded:
		const contentType = "application/x-www-form-urlencoded"
		request := req

		q := uri.NewFormEncoder(map[string]string{})
		{
			// Encode "name" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "name",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				return e.EncodeValue(conv.StringToString(request.Name))
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "description" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "description",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Description.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "color" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "color",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				return e.EncodeValue(conv.StringToString(request.Color))
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "sequence" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "sequence",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Sequence.Get(); ok {
					return e.EncodeValue(conv.Float64ToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "group" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "group",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Group.Get(); ok {
					return e.EncodeValue(conv.StringToString(string(val)))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "is_triage" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "is_triage",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.IsTriage.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "default" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "default",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Default.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "external_source" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "external_source",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.ExternalSource.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "external_id" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "external_id",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.ExternalID.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		encoded := q.Values().Encode()
		ht.SetBody(r, strings.NewReader(encoded), contentType)
		return nil
	case *StateRequestMultipart:
		const contentType = "multipart/form-data"
		request := req

		q := uri.NewFormEncoder(map[string]string{})
		{
			// Encode "name" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "name",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				return e.EncodeValue(conv.StringToString(request.Name))
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "description" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "description",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Description.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "color" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "color",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				return e.EncodeValue(conv.StringToString(request.Color))
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "sequence" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "sequence",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Sequence.Get(); ok {
					return e.EncodeValue(conv.Float64ToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "group" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "group",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Group.Get(); ok {
					return e.EncodeValue(conv.StringToString(string(val)))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "is_triage" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "is_triage",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.IsTriage.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "default" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "default",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Default.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "external_source" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "external_source",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.ExternalSource.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "external_id" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "external_id",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.ExternalID.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		body, boundary := ht.CreateMultipartBody(func(w *multipart.Writer) error {
			if err := q.WriteMultipart(w); err != nil {
				return errors.Wrap(err, "write multipart")
			}
			return nil
		})
		ht.SetCloserBody(r, body, mime.FormatMediaType(contentType, map[string]string{"boundary": boundary}))
		return nil
	default:
		return errors.Errorf("unexpected request type: %T", req)
	}
}

func encodeCreateWorkItem2Request(
	req CreateWorkItem2Req,
	r *http.Request,
) error {
	switch req := req.(type) {
	case *CreateWorkItem2ApplicationJSON:
		const contentType = "application/json"
		e := new(jx.Encoder)
		{
			req.Encode(e)
		}
		encoded := e.Bytes()
		ht.SetBody(r, bytes.NewReader(encoded), contentType)
		return nil
	case *CreateWorkItem2ApplicationXWwwFormUrlencoded:
		const contentType = "application/x-www-form-urlencoded"
		request := req

		q := uri.NewFormEncoder(map[string]string{})
		{
			// Encode "assignees" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "assignees",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if request.Assignees != nil {
					return e.EncodeArray(func(e uri.Encoder) error {
						for i, item := range request.Assignees {
							if err := func() error {
								return e.EncodeValue(conv.UUIDToString(item))
							}(); err != nil {
								return errors.Wrapf(err, "[%d]", i)
							}
						}
						return nil
					})
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "labels" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "labels",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if request.Labels != nil {
					return e.EncodeArray(func(e uri.Encoder) error {
						for i, item := range request.Labels {
							if err := func() error {
								return e.EncodeValue(conv.UUIDToString(item))
							}(); err != nil {
								return errors.Wrapf(err, "[%d]", i)
							}
						}
						return nil
					})
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "type_id" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "type_id",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.TypeID.Get(); ok {
					return e.EncodeValue(conv.UUIDToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "deleted_at" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "deleted_at",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.DeletedAt.Get(); ok {
					return e.EncodeValue(conv.DateTimeToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "point" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "point",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Point.Get(); ok {
					return e.EncodeValue(conv.IntToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "name" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "name",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				return e.EncodeValue(conv.StringToString(request.Name))
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "description_html" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "description_html",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.DescriptionHTML.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "priority" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "priority",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Priority.Get(); ok {
					return e.EncodeValue(conv.StringToString(string(val)))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "start_date" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "start_date",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.StartDate.Get(); ok {
					return e.EncodeValue(conv.DateToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "target_date" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "target_date",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.TargetDate.Get(); ok {
					return e.EncodeValue(conv.DateToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "sequence_id" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "sequence_id",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.SequenceID.Get(); ok {
					return e.EncodeValue(conv.Int64ToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "sort_order" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "sort_order",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.SortOrder.Get(); ok {
					return e.EncodeValue(conv.Float64ToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "archived_at" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "archived_at",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.ArchivedAt.Get(); ok {
					return e.EncodeValue(conv.DateToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "is_draft" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "is_draft",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.IsDraft.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "external_source" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "external_source",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.ExternalSource.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "external_id" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "external_id",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.ExternalID.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "created_by" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "created_by",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.CreatedBy.Get(); ok {
					return e.EncodeValue(conv.UUIDToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "parent" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "parent",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Parent.Get(); ok {
					return e.EncodeValue(conv.UUIDToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "state" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "state",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.State.Get(); ok {
					return e.EncodeValue(conv.UUIDToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "estimate_point" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "estimate_point",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.EstimatePoint.Get(); ok {
					return e.EncodeValue(conv.UUIDToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "type" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "type",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Type.Get(); ok {
					return e.EncodeValue(conv.UUIDToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		encoded := q.Values().Encode()
		ht.SetBody(r, strings.NewReader(encoded), contentType)
		return nil
	case *IssueRequestMultipart:
		const contentType = "multipart/form-data"
		request := req

		q := uri.NewFormEncoder(map[string]string{
			"priority": "application/json; charset=utf-8",
		})
		{
			// Encode "assignees" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "assignees",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if request.Assignees != nil {
					return e.EncodeArray(func(e uri.Encoder) error {
						for i, item := range request.Assignees {
							if err := func() error {
								return e.EncodeValue(conv.UUIDToString(item))
							}(); err != nil {
								return errors.Wrapf(err, "[%d]", i)
							}
						}
						return nil
					})
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "labels" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "labels",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if request.Labels != nil {
					return e.EncodeArray(func(e uri.Encoder) error {
						for i, item := range request.Labels {
							if err := func() error {
								return e.EncodeValue(conv.UUIDToString(item))
							}(); err != nil {
								return errors.Wrapf(err, "[%d]", i)
							}
						}
						return nil
					})
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "type_id" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "type_id",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.TypeID.Get(); ok {
					return e.EncodeValue(conv.UUIDToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "deleted_at" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "deleted_at",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.DeletedAt.Get(); ok {
					return e.EncodeValue(conv.DateTimeToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "point" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "point",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Point.Get(); ok {
					return e.EncodeValue(conv.IntToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "name" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "name",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				return e.EncodeValue(conv.StringToString(request.Name))
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "description_html" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "description_html",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.DescriptionHTML.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "priority" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "priority",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				var enc jx.Encoder
				func(e *jx.Encoder) {
					if request.Priority.Set {
						request.Priority.Encode(e)
					}
				}(&enc)
				return e.EncodeValue(string(enc.Bytes()))
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "start_date" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "start_date",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.StartDate.Get(); ok {
					return e.EncodeValue(conv.DateToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "target_date" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "target_date",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.TargetDate.Get(); ok {
					return e.EncodeValue(conv.DateToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "sequence_id" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "sequence_id",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.SequenceID.Get(); ok {
					return e.EncodeValue(conv.Int64ToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "sort_order" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "sort_order",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.SortOrder.Get(); ok {
					return e.EncodeValue(conv.Float64ToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "archived_at" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "archived_at",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.ArchivedAt.Get(); ok {
					return e.EncodeValue(conv.DateToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "is_draft" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "is_draft",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.IsDraft.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "external_source" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "external_source",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.ExternalSource.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "external_id" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "external_id",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.ExternalID.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "created_by" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "created_by",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.CreatedBy.Get(); ok {
					return e.EncodeValue(conv.UUIDToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "parent" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "parent",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Parent.Get(); ok {
					return e.EncodeValue(conv.UUIDToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "state" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "state",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.State.Get(); ok {
					return e.EncodeValue(conv.UUIDToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "estimate_point" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "estimate_point",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.EstimatePoint.Get(); ok {
					return e.EncodeValue(conv.UUIDToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "type" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "type",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Type.Get(); ok {
					return e.EncodeValue(conv.UUIDToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		body, boundary := ht.CreateMultipartBody(func(w *multipart.Writer) error {
			if err := q.WriteMultipart(w); err != nil {
				return errors.Wrap(err, "write multipart")
			}
			return nil
		})
		ht.SetCloserBody(r, body, mime.FormatMediaType(contentType, map[string]string{"boundary": boundary}))
		return nil
	default:
		return errors.Errorf("unexpected request type: %T", req)
	}
}

func encodeUpdateProjectRequest(
	req UpdateProjectReq,
	r *http.Request,
) error {
	switch req := req.(type) {
	case *UpdateProjectReqEmptyBody:
		// Empty body case.
		return nil
	case *UpdateProjectApplicationJSON:
		const contentType = "application/json"
		e := new(jx.Encoder)
		{
			req.Encode(e)
		}
		encoded := e.Bytes()
		ht.SetBody(r, bytes.NewReader(encoded), contentType)
		return nil
	case *UpdateProjectApplicationXWwwFormUrlencoded:
		const contentType = "application/x-www-form-urlencoded"
		request := req

		q := uri.NewFormEncoder(map[string]string{})
		{
			// Encode "name" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "name",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Name.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "description" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "description",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Description.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "project_lead" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "project_lead",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.ProjectLead.Get(); ok {
					return e.EncodeValue(conv.UUIDToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "default_assignee" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "default_assignee",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.DefaultAssignee.Get(); ok {
					return e.EncodeValue(conv.UUIDToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "identifier" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "identifier",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Identifier.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "icon_prop" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "icon_prop",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if request.IconProp != nil {
					return e.EncodeValue(fmt.Sprint(request.IconProp))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "emoji" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "emoji",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Emoji.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "cover_image" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "cover_image",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.CoverImage.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "module_view" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "module_view",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.ModuleView.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "cycle_view" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "cycle_view",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.CycleView.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "issue_views_view" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "issue_views_view",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.IssueViewsView.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "page_view" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "page_view",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.PageView.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "intake_view" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "intake_view",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.IntakeView.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "guest_view_all_features" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "guest_view_all_features",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.GuestViewAllFeatures.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "archive_in" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "archive_in",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.ArchiveIn.Get(); ok {
					return e.EncodeValue(conv.IntToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "close_in" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "close_in",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.CloseIn.Get(); ok {
					return e.EncodeValue(conv.IntToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "timezone" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "timezone",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Timezone.Get(); ok {
					return e.EncodeValue(conv.StringToString(string(val)))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "external_source" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "external_source",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.ExternalSource.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "external_id" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "external_id",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.ExternalID.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "is_issue_type_enabled" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "is_issue_type_enabled",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.IsIssueTypeEnabled.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "is_time_tracking_enabled" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "is_time_tracking_enabled",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.IsTimeTrackingEnabled.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "default_state" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "default_state",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.DefaultState.Get(); ok {
					return e.EncodeValue(conv.UUIDToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "estimate" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "estimate",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Estimate.Get(); ok {
					return e.EncodeValue(conv.UUIDToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		encoded := q.Values().Encode()
		ht.SetBody(r, strings.NewReader(encoded), contentType)
		return nil
	case *PatchedProjectUpdateRequestMultipart:
		const contentType = "multipart/form-data"
		request := req

		q := uri.NewFormEncoder(map[string]string{
			"icon_prop": "application/json; charset=utf-8",
		})
		{
			// Encode "name" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "name",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Name.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "description" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "description",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Description.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "project_lead" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "project_lead",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.ProjectLead.Get(); ok {
					return e.EncodeValue(conv.UUIDToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "default_assignee" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "default_assignee",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.DefaultAssignee.Get(); ok {
					return e.EncodeValue(conv.UUIDToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "identifier" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "identifier",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Identifier.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "icon_prop" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "icon_prop",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				var enc jx.Encoder
				func(e *jx.Encoder) {
					if len(request.IconProp) != 0 {
						e.Raw(request.IconProp)
					}
				}(&enc)
				return e.EncodeValue(string(enc.Bytes()))
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "emoji" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "emoji",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Emoji.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "cover_image" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "cover_image",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.CoverImage.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "module_view" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "module_view",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.ModuleView.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "cycle_view" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "cycle_view",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.CycleView.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "issue_views_view" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "issue_views_view",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.IssueViewsView.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "page_view" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "page_view",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.PageView.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "intake_view" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "intake_view",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.IntakeView.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "guest_view_all_features" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "guest_view_all_features",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.GuestViewAllFeatures.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "archive_in" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "archive_in",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.ArchiveIn.Get(); ok {
					return e.EncodeValue(conv.IntToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "close_in" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "close_in",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.CloseIn.Get(); ok {
					return e.EncodeValue(conv.IntToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "timezone" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "timezone",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Timezone.Get(); ok {
					return e.EncodeValue(conv.StringToString(string(val)))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "external_source" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "external_source",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.ExternalSource.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "external_id" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "external_id",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.ExternalID.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "is_issue_type_enabled" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "is_issue_type_enabled",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.IsIssueTypeEnabled.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "is_time_tracking_enabled" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "is_time_tracking_enabled",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.IsTimeTrackingEnabled.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "default_state" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "default_state",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.DefaultState.Get(); ok {
					return e.EncodeValue(conv.UUIDToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "estimate" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "estimate",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Estimate.Get(); ok {
					return e.EncodeValue(conv.UUIDToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		body, boundary := ht.CreateMultipartBody(func(w *multipart.Writer) error {
			if err := q.WriteMultipart(w); err != nil {
				return errors.Wrap(err, "write multipart")
			}
			return nil
		})
		ht.SetCloserBody(r, body, mime.FormatMediaType(contentType, map[string]string{"boundary": boundary}))
		return nil
	default:
		return errors.Errorf("unexpected request type: %T", req)
	}
}

func encodeUpdateWorkItem2Request(
	req UpdateWorkItem2Req,
	r *http.Request,
) error {
	switch req := req.(type) {
	case *UpdateWorkItem2ReqEmptyBody:
		// Empty body case.
		return nil
	case *UpdateWorkItem2ApplicationJSON:
		const contentType = "application/json"
		e := new(jx.Encoder)
		{
			req.Encode(e)
		}
		encoded := e.Bytes()
		ht.SetBody(r, bytes.NewReader(encoded), contentType)
		return nil
	case *UpdateWorkItem2ApplicationXWwwFormUrlencoded:
		const contentType = "application/x-www-form-urlencoded"
		request := req

		q := uri.NewFormEncoder(map[string]string{})
		{
			// Encode "assignees" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "assignees",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if request.Assignees != nil {
					return e.EncodeArray(func(e uri.Encoder) error {
						for i, item := range request.Assignees {
							if err := func() error {
								return e.EncodeValue(conv.UUIDToString(item))
							}(); err != nil {
								return errors.Wrapf(err, "[%d]", i)
							}
						}
						return nil
					})
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "labels" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "labels",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if request.Labels != nil {
					return e.EncodeArray(func(e uri.Encoder) error {
						for i, item := range request.Labels {
							if err := func() error {
								return e.EncodeValue(conv.UUIDToString(item))
							}(); err != nil {
								return errors.Wrapf(err, "[%d]", i)
							}
						}
						return nil
					})
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "type_id" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "type_id",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.TypeID.Get(); ok {
					return e.EncodeValue(conv.UUIDToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "deleted_at" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "deleted_at",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.DeletedAt.Get(); ok {
					return e.EncodeValue(conv.DateTimeToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "point" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "point",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Point.Get(); ok {
					return e.EncodeValue(conv.IntToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "name" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "name",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Name.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "description_html" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "description_html",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.DescriptionHTML.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "priority" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "priority",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Priority.Get(); ok {
					return e.EncodeValue(conv.StringToString(string(val)))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "start_date" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "start_date",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.StartDate.Get(); ok {
					return e.EncodeValue(conv.DateToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "target_date" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "target_date",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.TargetDate.Get(); ok {
					return e.EncodeValue(conv.DateToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "sequence_id" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "sequence_id",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.SequenceID.Get(); ok {
					return e.EncodeValue(conv.Int64ToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "sort_order" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "sort_order",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.SortOrder.Get(); ok {
					return e.EncodeValue(conv.Float64ToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "archived_at" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "archived_at",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.ArchivedAt.Get(); ok {
					return e.EncodeValue(conv.DateToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "is_draft" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "is_draft",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.IsDraft.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "external_source" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "external_source",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.ExternalSource.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "external_id" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "external_id",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.ExternalID.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "created_by" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "created_by",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.CreatedBy.Get(); ok {
					return e.EncodeValue(conv.UUIDToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "parent" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "parent",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Parent.Get(); ok {
					return e.EncodeValue(conv.UUIDToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "state" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "state",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.State.Get(); ok {
					return e.EncodeValue(conv.UUIDToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "estimate_point" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "estimate_point",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.EstimatePoint.Get(); ok {
					return e.EncodeValue(conv.UUIDToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "type" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "type",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Type.Get(); ok {
					return e.EncodeValue(conv.UUIDToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		encoded := q.Values().Encode()
		ht.SetBody(r, strings.NewReader(encoded), contentType)
		return nil
	case *PatchedIssueRequestMultipart:
		const contentType = "multipart/form-data"
		request := req

		q := uri.NewFormEncoder(map[string]string{
			"priority": "application/json; charset=utf-8",
		})
		{
			// Encode "assignees" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "assignees",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if request.Assignees != nil {
					return e.EncodeArray(func(e uri.Encoder) error {
						for i, item := range request.Assignees {
							if err := func() error {
								return e.EncodeValue(conv.UUIDToString(item))
							}(); err != nil {
								return errors.Wrapf(err, "[%d]", i)
							}
						}
						return nil
					})
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "labels" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "labels",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if request.Labels != nil {
					return e.EncodeArray(func(e uri.Encoder) error {
						for i, item := range request.Labels {
							if err := func() error {
								return e.EncodeValue(conv.UUIDToString(item))
							}(); err != nil {
								return errors.Wrapf(err, "[%d]", i)
							}
						}
						return nil
					})
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "type_id" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "type_id",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.TypeID.Get(); ok {
					return e.EncodeValue(conv.UUIDToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "deleted_at" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "deleted_at",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.DeletedAt.Get(); ok {
					return e.EncodeValue(conv.DateTimeToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "point" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "point",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Point.Get(); ok {
					return e.EncodeValue(conv.IntToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "name" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "name",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Name.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "description_html" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "description_html",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.DescriptionHTML.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "priority" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "priority",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				var enc jx.Encoder
				func(e *jx.Encoder) {
					if request.Priority.Set {
						request.Priority.Encode(e)
					}
				}(&enc)
				return e.EncodeValue(string(enc.Bytes()))
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "start_date" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "start_date",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.StartDate.Get(); ok {
					return e.EncodeValue(conv.DateToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "target_date" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "target_date",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.TargetDate.Get(); ok {
					return e.EncodeValue(conv.DateToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "sequence_id" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "sequence_id",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.SequenceID.Get(); ok {
					return e.EncodeValue(conv.Int64ToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "sort_order" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "sort_order",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.SortOrder.Get(); ok {
					return e.EncodeValue(conv.Float64ToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "archived_at" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "archived_at",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.ArchivedAt.Get(); ok {
					return e.EncodeValue(conv.DateToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "is_draft" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "is_draft",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.IsDraft.Get(); ok {
					return e.EncodeValue(conv.BoolToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "external_source" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "external_source",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.ExternalSource.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "external_id" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "external_id",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.ExternalID.Get(); ok {
					return e.EncodeValue(conv.StringToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "created_by" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "created_by",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.CreatedBy.Get(); ok {
					return e.EncodeValue(conv.UUIDToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "parent" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "parent",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Parent.Get(); ok {
					return e.EncodeValue(conv.UUIDToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "state" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "state",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.State.Get(); ok {
					return e.EncodeValue(conv.UUIDToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "estimate_point" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "estimate_point",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.EstimatePoint.Get(); ok {
					return e.EncodeValue(conv.UUIDToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		{
			// Encode "type" form field.
			cfg := uri.QueryParameterEncodingConfig{
				Name:    "type",
				Style:   uri.QueryStyleForm,
				Explode: true,
			}
			if err := q.EncodeParam(cfg, func(e uri.Encoder) error {
				if val, ok := request.Type.Get(); ok {
					return e.EncodeValue(conv.UUIDToString(val))
				}
				return nil
			}); err != nil {
				return errors.Wrap(err, "encode query")
			}
		}
		body, boundary := ht.CreateMultipartBody(func(w *multipart.Writer) error {
			if err := q.WriteMultipart(w); err != nil {
				return errors.Wrap(err, "write multipart")
			}
			return nil
		})
		ht.SetCloserBody(r, body, mime.FormatMediaType(contentType, map[string]string{"boundary": boundary}))
		return nil
	default:
		return errors.Errorf("unexpected request type: %T", req)
	}
}
